## Source functions

```{r}
source("../R/99_proj_func.R")
```

## Loading packages

```{r}
list.of.packages <- c("tidyverse", 
                      "readxl", 
                      "Racmacs", 
                      "viridis", 
                      "ggrepel", 
                      "svglite", 
                      "knitr",  # FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX FIX 
                      "dbscan", 
                      "ggforce", 
                      "RColorBrewer")
new.packages <- list.of.packages[!(
  list.of.packages %in% installed.packages()[
    ,"Package"
    ]
  )]
if(length(new.packages)) 
  install.packages(new.packages)
```



## Libraries

```{r}
#| eval: true
#| echo: false
#| message: false
#| warning: false

library("tidyverse")
library("readxl")

# https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
```

# Antigenic Cartography - COVID

Antigen names; H69775 (Wuhan), Alpha (B.1.1.7), Beta (B.1.351), Gamma (P.1), Delta B.1.617.2, Delta AY.33, Delta AY.4, Delta AY.4.2, Delta B.1.617.2 and E484K Omicron

## Generate data directories
```{r}
make_dir("../data")
make_dir("../data/_raw")

```

## Loading excel file

```{r}

# Use file.choose() for the user to select the file
# file_path <- file.choose()

# Now read the selected Excel file
# excel_data <- readxl::read_excel(file_path)

# Check if the data has been loaded correctly
#if (!is.null(excel_data)) {message("Data loaded successfully.")} 
#else {message("Failed to load data.")}


excel_data <- read_excel("../data/_raw/acmap_covid.xlsx")  ## AUTOMATE
## SPØRG MARTHA
## SPØRG MARTHA
## SPØRG MARTHA

write_csv(excel_data, "../data/excel_csv.csv.gz")
```


## Loading data
```{r}
#| echo: false
#| message: false
#| output: false

## Loading titer data from pre-made csv file
#titer_table <- read_csv2(file = "../_raw/antigenic_map_template_covid.csv")

## Loading titer data from generated csv file
titer_table <- read_csv(file = "../data/excel_csv.csv.gz")


```

## Writing files
```{r}

## Writing titer file
write_tsv(titer_table,
            file = "../data/titer_dirty.tsv.gz")

```
