---
title: "virus titration"
format: html
editor: source
author: Oliver
---

### Source functions

```{r}
source("../R/99_proj_func.R")
```

### Libraries:

```{r}

library("tidyverse")
library("httr")
library("jsonlite")
library("dplyr")
library("R.utils")

```

### Generate data directories

```{r}
make_dir("../_raw")
make_dir("../data")
```

### Load files:

```{r}
#name_prompt = readline(prompt = "State the exact name of the file : ");
#Something cool where it knows what to load and stuff

#Right now we do the primitive way
titration_data_OLSE <- read_csv2(file = "../_raw/H6N1 california titration OLSE230124.csv")
titration_data_MOAJ <- read_csv2(file = "../_raw/H6N1 california titration MAOJ230124.csv")

View(titration_data_OLSE)
View(titration_data_MOAJ)
```

### Extracting the plate data

```{r}
#Extrats the correct table
titration_data_extract <- titration_data_MOAJ[13:16, 2:13]
View(titration_data_extract)

#Tries to rename the columns but does not work
titration_data_extract <- titration_data_extract |> rename_with(~seq_along(.))

#Extracts background reading
titration_data_background <- titration_data_MOAJ[24:27, 2:13]

#Tries to get 
titration_data_extract - titration_data_background


#Generates a vector for naming 1:12
vector_name <- 1:12



class(titration_data_background)
```
